planner_name: confidence_pano
type: confidence_pano
radius: 2.0 # action space radius in meters
init_pose: [[0, 0, 1, 0], [-1, 0, 0, 0], [0, -1, 0, 0], [0, 0, 0, 1]] # opencv camera in world coordiante
robot_size: 0.3

### sampling related
pitch_angle: null
sample_num: 50
max_roi_sample_num: 0
use_confidence: false
path_length_factor: 0.5
use_perspective: false

### planner specific
render_ratio: 0.25
explore_weight: 1000.0